spring:
  server:
    port: 8080
    servlet:
      context-path: /vault
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb+srv://arshbhushan:cPGBrvFTl3M9Xzqw@cluster0.qag6g.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: decentraVaultDB
      auto-index-creation: true
#  redis:
#    uri: redis-12663.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
#    port: 12663
#    password: U8qkfPM9LzRHcWzGkAyMai8d9lAeqwCh
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: arshbhushan@gmail.com
#    password: icxh rqwa mqqp tbko
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  kafka:
#    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: weekly-sentiment-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: com.learningSB.journalApp.model
#    properties:
#      sasl.mechanism: PLAIN
#      security.protocol: SASL_SSL
#      sasl.jaas.config: |
#        org.apache.kafka.common.security.plain.PlainLoginModule required
#        username="7WLQMWO4YSSBNT4T"
#        password="+3GH37BzG64vtmzOJzznRVKBwuUXsPXnJCS7govFTZ7TBihw3bkegNos5Oxpb7BM";
#      session.timeout.ms: 45000
#      client-id: ccloud-springboot-client-6cd7f95e-7fd4-4d76-8bd1-9cbd9bff28c1
#
logging:
  level:
    org.springframework.security: DEBUG
